version: '2.32.1'
services:

  redis:
    container_name: redis-precit
    image: redis:6.2-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server
    volumes: 
      - redis:/data
    networks:
      - fr2-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  web: 
    container_name: api-predict
    build:
      context: ./
      target: builder
    ports: 
      - '8000:8000'
    depends_on:
      - redis
    networks:
      - fr2-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  predictor_service: 
    container_name: predictor_service
    restart: always
    build:
      context: predict-service
      target: builder
    depends_on:
      - redis
    networks:
      - fr2-network
    extra_hosts:
      - "host.docker.internal:host-gateway"

  mongodb:
    image: mvertes/alpine-mongo
    container_name: mongodb
    environment:
      - MONGODB_INITDB_ROOT_USERNAME=user
      - MONGODB_INITDB_ROOT_PASSWORD=pass
    volumes:
      - mongo-data:/data/db
    networks:
      - fr2-network
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 27017:27017

volumes:
  mongo-data:
    driver: local
  redis:
    driver: local

networks:
  fr2-network:
    driver: bridge
